import type {BoardGame} from "./types/boardGame.ts";

export const mockGames: BoardGame[] = [
    {
        id: '1',
        name: 'CATAN',
        minPlayers: 3,
        maxPlayers: 4,
        language: 'English',
        genres: ['Strategy', 'Family'],
        boxImageFrontUrl: 'https://s.hdnux.com/photos/22/65/76/4939709/3/1200x0.jpg',
        boxImageBackUrl: 'https://preview.redd.it/a0q939r12ii81.jpg?width=1991&format=pjpg&auto=webp&s=442d79283e7bff90fbeae744d062821c7dc93d4d',
        rulesPdfUrl: 'https://www.catan.com/sites/default/files/2025-03/CN3081%20CATAN%E2%80%93The%20Game%20Rulebook%20secure%20%281%29.pdf',
    },
    {
        id: '2',
        name: 'Pandemic',
        minPlayers: 2,
        maxPlayers: 4,
        language: 'English',
        genres: ['Co‑op', 'Strategy'],
        boxImageFrontUrl: 'https://d.newsweek.com/en/full/1665034/pandemic-box-art.jpg?w=1200&f=59312c93f3157456d29f1278abd35f05',
        boxImageBackUrl: 'https://www.kroger.com/product/images/large/back/0068170671100',
        // no PDF provided
    },
    {
        id: '3',
        name: 'Ticket to Ride',
        minPlayers: 2,
        maxPlayers: 5,
        language: 'German',
        genres: ['Family', 'Strategy'],
        boxImageFrontUrl: 'https://upload.wikimedia.org/wikipedia/en/9/92/Ticket_to_Ride_Board_Game_Box_EN.jpg',
        boxImageBackUrl: 'https://cdn.svc.asmodee.net/production-asmodeenordics/uploads/image-converter/2022/01/7201-T2R-box-back-EN-1016x1024.webp',
        rulesPdfUrl: 'https://cdn.1j1ju.com/medias/2c/f9/7f-ticket-to-ride-rulebook.pdf',
    },
    {
        id: '4',
        name: 'Azul',
        minPlayers: 2,
        maxPlayers: 4,
        language: 'French',
        genres: ['Strategy', 'Abstract'],
        boxImageFrontUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/23/Picture_of_Azul_game_box.jpg/250px-Picture_of_Azul_game_box.jpg',
        boxImageBackUrl: 'https://brettspieler.de/cdn/shop/products/AzulBack_800x.jpg?v=1615547200',
    },
    {
        id: '5',
        name: 'Dixit',
        minPlayers: 3,
        maxPlayers: 6,
        language: 'English',
        genres: ['Party', 'Family'],
        boxImageFrontUrl: 'https://www.brettspielversand.de/media/image/product/1381/lg/dixit.jpg',
        boxImageBackUrl: 'https://cf.geekdo-images.com/EtMg503OkG4zvO07DbK8HA__imagepage/img/FXWd7g_4c2MR5SxhPFym4qGEuBw=/fit-in/900x600/filters:no_upscale():strip_icc()/pic4421117.jpg',
        rulesPdfUrl: 'https://cdn.1j1ju.com/medias/8f/03/3d-dixit-rulebook.pdf',
    },
    {
        id: '6',
        name: '7 Wonders',
        minPlayers: 2,
        maxPlayers: 7,
        language: 'English',
        genres: ['Strategy', 'Card'],
        boxImageFrontUrl: 'https://media.brettspiel-angebote.de/2015/04/box-7-wonders.jpg',
        boxImageBackUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBhTDKPY9Rw5dxPMS2M_6VDdtL_KobAN8SXA&s',
    },
]
